apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with .Values.postgui.ingressAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.postgui.hostUrl }}
      http:
        paths:
          - path: /.*
            pathType: Prefix
            backend:
              service:
                name: postgui
                port:
                  number: 8771
