apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-admin-password
data:
  password: {{ .Values.postgresDb.adminPassword | b64enc | quote }}
  user: {{ .Values.postgresDb.adminUser | b64enc | quote }}
  url: {{ printf "postgresql://%s:%s@postgres.%s.svc.cluster.local:5432/%s" .Values.postgresDb.adminUser .Values.postgresDb.adminPassword .Release.Namespace .Values.postgresDb.dbName | b64enc | quote }}
